name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - '*'
      - '!master'

jobs:
  ci:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Lint check
        run: pnpm lint:check

      - name: Build
        run: pnpm build

      - name: Run Tests
        run: pnpm test:coverage

      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v3
